name: SAST Horusec Scan

on:
  push:
    branches:
      - master

jobs:
  checking_code:
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v3
          with: # Required when commit authors is enabled
            fetch-depth: 0
        - name: Running Horusec Security
          continue-on-error: true
          run: |
            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
            horusec start -p="./" -e="true" -D = "true" -o="json" -O="./horusec.json" --information-severity=true
        - uses: actions/upload-artifact@v3
          with:
            name: horusec
            path: horusec.json 