name: GitGuardian iac scan

on: [push, pull_request]

jobs:
  scanning:
    name: iac scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian iac scan
        uses: GitGuardian/ggshield/actions/iac@main
        with:
          args: ./terraform/ --minimum-severity CRITICAL # pass arguments to the action. If missing, will scan the current directory
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}